site_name: My Docs

theme:
  name: material

  # 自定义外观
  palette:
    # 调色板方案，第一个是默认模式，第二个是暗黑模式可选
    - scheme: default
      toggle:
        icon: material/brightness-7 # 太阳图标，代表亮模式
        name: 切换到暗黑模式
    - scheme: slate
      toggle:
        icon: material/brightness-4 # 月亮图标，代表暗模式
        name: 切换到明亮模式
  features:
    - navigation.tabs # 启用顶部标签页（用于导航）
    - navigation.sections # 在导航栏中显示章节
    - toc.integrate # 将目录集成到侧边栏
    - navigation.expand # 默认展开当前页面的导航节点
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - content.code.annotate # 代码注释

# 插件
plugins:
  - search

# 导航配置

# 扩展
markdown_extensions:
  - admonition # 启用警告提示框
  - pymdownx.details # 启用折叠区块
  - pymdownx.superfences # 更强大的代码块
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.tabbed: # 启用内容标签页
      alternate_style: true
